name: Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run Tests and Generate Report
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with Allure
      run: |
        cd src
        behave -f allure_behave.formatter:AllureFormatter -o ../reports/allure-results ./features

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: reports/allure-results
        allure_report: allure-report

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      if: always()
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      id: deployment
      if: always()
      uses: actions/deploy-pages@v1