name: Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run Tests and Generate Report
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with Allure
      run: |
        # Start ChromeDriver
        chromedriver --version
        google-chrome --version
        
        # Start ChromeDriver in the background
        chromedriver &
        
        # Run tests
        cd src
        behave -f allure_behave.formatter:AllureFormatter -o ../reports/allure-results ./features

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: reports/allure-results
        allure_report: allure-report

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      if: always()
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      id: deployment
      if: always()
      uses: actions/deploy-pages@v1